AWSTemplateFormatVersion: 2010-09-09
Description: >-
  "test-template-bucket"

Parameters:
  Env:
    Type: String
    Default: "dev"
    AllowedValues: ["dev", "stg", "prd"]
  ResourceName:
    Type: String
    Default: "test-project"

Resources:
  # ------------------------------ #
  # S3Bucket
  # ------------------------------ #
  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Env}-${ResourceName}-bucket"
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true