AWSTemplateFormatVersion: 2010-09-09
Description: >-
  "test-rds"

Parameters:
  Env:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'stg', 'prd']
  ResourceName:
    Type: String
    Default: 'test-project'

  DBInstanceID:
    Type: String
    Default: db
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBName:
    Type: String
    Default: mydb
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  DBUsername:
    Type: String
    Default: admin
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.t2.micro
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Type: Number
    Default: 20
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBEngineVersion:
    Type: String
    Default: 8.0.33

Resources:
  # ------------------------------ #
  # RDSInstance
  # ------------------------------ #
  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: MySQL
      DBInstanceIdentifier: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', !Ref 'DBInstanceID']]
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      EngineVersion: !Ref DBEngineVersion
      VPCSecurityGroups: 
        - !ImportValue testDbSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
  # ------------------------------ #
  # DBSubnetGroup
  # ------------------------------ #
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: description
      DBSubnetGroupName: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'DBSubnetGroup']]
      SubnetIds: 
        - !ImportValue 'testPrivateSubnet1a'
        - !ImportValue 'testPrivateSubnet1c'
      Tags: 
        - Key: String
          Value: !Join ['-', [!Ref 'Env', !Ref 'ResourceName', 'DBSubnetGroup']]

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub 'testRDSEndpoint'